<?php
/**
 * @file
 * MathJax module.
 */

/**
 * Implements hook_help().
 */
function mathjax_help($path, $arg) {
  switch ($path) {
    // Main module help for the mathjax module.
    case 'admin/config/content/mathjax':
      return t('MathJax allows you to include mathematics in your web pages, either using TeX and LaTeX notation, or as MathML, and you can even use both in the same document. Go to the <a href="@url">MathJax website</a> for more information.', array('@url' => url('http://www.mathjax.org/')));

    case 'admin/help#mathjax':
      return '<p>' . t('MathJax allows you to include mathematics in your web pages, either using TeX and LaTeX notation, or as MathML, and you can even use both in the same document. Go to the <a href="@url">MathJax website</a> for more information.', array('@url' => url('http://www.mathjax.org/'))) . '</p>';
  }
}

/**
 * Implements hook_page_attachments().
 */
function mathjax_page_attachments(&$page) {
  $config = Drupal::config('mathjax.settings');
  $config_type = $config->get('config_type');
  if ($config_type == 1) {
    $config_string = $config->get('config_string');
    $page['#attached']['drupalSettings']['mathjax'] = [
      'config_type' => $config_type,
      'config_string' => $config_string,
    ];
    $page['#attached']['library'][] = 'mathjax/config';
    $page['#attached']['library'][] = 'mathjax/source';
    $page['#attached']['library'][] = 'mathjax/setup';
  }
}

/**
 * Implements hook_js_alter().
 */
function mathjax_js_alter(&$javascript) {
  $config = Drupal::config('mathjax.settings');
  if ($config->get('use_cdn', TRUE)) {
    $javascript['MathJax.js']['data'] = $config->get('cdn_url');
  }
  else {
    if (function_exists('libraries_get_path')) {
      $javascript['MathJax.js']['data'] = libraries_get_path('mathjax', TRUE) . '/MathJax.js?config=TeX-AMS-MML_HTMLorMML';
    }
  }
}
