<?php
/**
 * @file
 * MathJax module.
 */

/**
 * Default values for MathJax configuration. May be overridden in the config.
 *
 * @param string $parameter
 *   Decides which default config to fetch. Either 'cdn url' or 'config string'.
 *
 * @return string
 *   The default configuration.
 */
function mathjax_default($parameter) {
  switch ($parameter) {
    case 'cdn url':
      return 'https://c328740.ssl.cf1.rackcdn.com/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML';
    case 'config string':
      return "
MathJax.Hub.Config({
  extensions: ['tex2jax.js'],
  jax: ['input/TeX','output/HTML-CSS'],
  tex2jax: {
    inlineMath: [ ['$','$'], ['\\\\(','\\\\)'] ],
    processEscapes: true,
    processClass: 'tex2jax',
    ignoreClass: 'html'
  },
  showProcessingMessages: false,
  messageStyle: 'none'
});
";
    default:
      return;
  }
}

/**
 * Implements hook_help().
 */
function mathjax_help($path, $arg) {
  switch ($path) {
    // Main module help for the mathjax module.
    case 'admin/config/content/mathjax':
      return t('MathJax allows you to include mathematics in your web pages, either using TeX and LaTeX notation, or as MathML, and you can even use both in the same document. Go to the <a href="@url">MathJax website</a> for more information.', array('@url' => url('http://www.mathjax.org/')));

    case 'admin/help#mathjax':
      return '<p>' . t('MathJax allows you to include mathematics in your web pages, either using TeX and LaTeX notation, or as MathML, and you can even use both in the same document. Go to the <a href="@url">MathJax website</a> for more information.', array('@url' => url('http://www.mathjax.org/'))) . '</p>';
  }
}

/**
 * Implements hook_page_build().
 */
function mathjax_page_build(&$page) {
  global $base_path;
  $config = Drupal::config('mathjax.settings');

  if ($config->get('mathjax_config_type') == 0) {
    $config_string = mathjax_default('config string');
  }
  else {
    $config_string = !is_null($config->get('mathjax_config_string')) ? $config->get('mathjax_config_string') : mathjax_default('config string');
  }
  // Load Mathjax.
  $config_string_wrapped = array(
    '#type' => 'markup',
    '#markup' => '<script type="text/x-mathjax-config">' . $config_string . '</script>',
  );
  $page['#attached']['drupal_add_html_head'] = array(
    array($config_string_wrapped, 'mathjax-config'),
  );
  $page['#attached']['js'][drupal_get_path('module', 'mathjax') . '/mathjax.js'] = array(
    'every_page' => TRUE,
  );
  if (!is_null($config->get('mathjax_use_cdn')) ? $config->get('mathjax_use_cdn') : TRUE) {
    $cdn_url = !is_null($config->get('mathjax_cdn_url')) ? $config->get('mathjax_cdn_url') : mathjax_default('cdn url');
    $page['#attached']['js'][$cdn_url] = array('every_page' => TRUE, 'type' => 'external');
  }
  else {
    // Use the local library.
    $library = DRUPAL_ROOT . $base_path . libraries_get_path('mathjax') . '/MathJax.js';
    if (file_exists($library)) {
      $page['#attached']['js'][$base_path . libraries_get_path('mathjax') . '/MathJax.js?config=TeX-AMS-MML_HTMLorMML'] = array('every_page' => TRUE, 'type' => 'external');
    }
    else {
      // Throw an error.
      drupal_set_message('MathJax is configured to load from a local library, but could not find the library files. Check the module settings.', 'error');
    }
  }
}

/**
 * Implements hook_permission().
 */
function mathjax_permission() {
  return array(
    'administer mathjax' => array(
      'title' => t('Administer MathJax'),
    ),
  );
}

/**
 * Implements hook_menu().
 */
function mathjax_menu() {

  $items['mathjax_settings'] = array(
    'title' => 'MathJax',
    'description' => 'Configure global settings for MathJax.',
    'route_name' => 'mathjax.settings',
  );

  return $items;
}
